### ISSUE TITLE
Config: `commands.pass.clipboard-duration` should have special behavior on 0

### ISSUE THREAD

**Issue by woodruffw** [woodruffw/kbs2#15]
Setting the following:

```toml
[commands.pass]
clipboard-duration = 0
```

Should cause the clipboard contents to be persisted indefinitely.
